- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas

- osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: int
    value: 1
    state: present

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: dockitems_to_remove

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: dockitems_to_persist

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: dockitems_to_persist

- osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: int
    value: 1
    state: present

- osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: int
    value: 1
    state: present

- osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: bottom
    state: present

- osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 51
    state: present

